const fs = require("node:fs");
const path = require("node:path");
const MarkdownIt = require("markdown-it");
const texmath = require("markdown-it-texmath");
const katex = require("katex");
const footnote = require("markdown-it-footnote");
const taskLists = require("markdown-it-task-lists");
const sanitize = require("sanitize-html");
const { resolveImages } = require("./images.cjs");
const { layoutHints, layoutAllowedAttributes } = require("./html-layout.cjs");
const { checkMarkdown } = require("./diagnostics/index.cjs");

const escape = (value) =>
  String(value).replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ],
  );
const { layoutCss } = require("./layout.cjs");
const { mathCss } = require("./math-fonts.cjs");
const documentCss = fs.readFileSync(
  path.join(__dirname, "../../resources/styles/document.css"),
  "utf8",
);

async function buildDocument(file, options = {}) {
  const strings = require("../shared/strings.json")[options.language || "zh"];
  if (fs.statSync(file).size > 10 * 1024 * 1024)
    throw new Error(strings.fileTooLarge);
  const source = fs.readFileSync(file, "utf8");
  const warnings = [];
  const layoutWarnings = [];
  const warnLayout = (key) => {
    if (!layoutWarnings.some((warning) => warning.key === key))
      layoutWarnings.push({ key });
  };
  const md = new MarkdownIt({ html: true, linkify: true })
    .use(footnote)
    .use(taskLists)
    .use(texmath, {
      engine: katex,
      delimiters: "dollars",
      katexOptions: {
        output: "html",
        throwOnError: false,
        trust: false,
        maxExpand: 1000,
      },
    });
  const slugs = new Set();
  const originalHeading = md.renderer.rules.heading_open;
  md.renderer.rules.table_open = (tokens, index, opts, env, self) => {
    tokens[index].attrJoin("class", "aldus-markdown-table");
    return self.renderToken(tokens, index, opts);
  };
  md.renderer.rules.heading_open = (tokens, index, opts, env, self) => {
    // Slug visible inline text, not Markdown source (which includes link URLs).
    const title = (tokens[index + 1].children || [])
      .filter((token) =>
        ["text", "code_inline", "image", "math_inline"].includes(token.type),
      )
      .map((token) => token.content)
      .join("");
    const slug = title
      .toLowerCase()
      .replace(/[^\p{L}\p{N}\p{M} _-]/gu, "")
      .replace(/ /g, "-");
    let unique = slug,
      count = 0;
    while (slugs.has(unique)) unique = `${slug}-${++count}`;
    slugs.add(unique);
    tokens[index].attrSet("id", unique);
    return originalHeading
      ? originalHeading(tokens, index, opts, env, self)
      : self.renderToken(tokens, index, opts);
  };
  const base = fs.realpathSync(path.dirname(file));
  const env = {};
  const checked = checkMarkdown(source, md);
  const tokens = md.parse(checked.source, env);
  for (const token of tokens) {
    if (
      token.type === "fence" &&
      /^(?:mermaid|plantuml|dot|graphviz)\b/i.test(token.info.trim())
    )
      warnLayout("diagramSource");
    // Only authored HTML, not SVG generated by KaTeX.
    const html = token.type.startsWith("html_")
      ? token.content
      : (token.children || [])
          .filter((child) => child.type.startsWith("html_"))
          .map((child) => child.content)
          .join("");
    if (/<svg\b/i.test(html)) warnLayout("inlineSvg");
    if (html)
      sanitize(html, {
        onOpenTag: (tag, attrs) => {
          if (attrs.id) slugs.add(attrs.id);
          if (tag === "a" && attrs.name) slugs.add(attrs.name);
        },
      });
  }
  const rendered = md.renderer.render(tokens, md.options, env);
  const sources = [];
  sanitize(rendered, {
    transformTags: {
      img: (tagName, attrs) => {
        sources.push(attrs.src || "");
        return { tagName, attribs: attrs };
      },
    },
  });
  const images = await resolveImages(sources, base, options.remoteLoader);
  const inspectCss = (css) => {
    if (/@import\b/i.test(css)) warnLayout("externalStyles");
    for (const match of css.matchAll(
      /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)]*))\)/gi,
    )) {
      if (!/^(?:data:|#)/i.test((match[1] ?? match[2] ?? match[3]).trim()))
        warnLayout("cssResources");
    }
  };
  for (const match of rendered.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi))
    inspectCss(match[1]);
  const tables = [];
  const hintRules = [];
  const body = sanitize(rendered, {
    onOpenTag: (tag, attrs) => {
      if (tag === "table") tables.push(attrs);
      if (attrs.style) inspectCss(attrs.style);
      if (
        tag === "link" &&
        /(?:^|\s)stylesheet(?:\s|$)/i.test(attrs.rel || "")
      ) {
        warnLayout("externalStyles");
      } else if (["script", "iframe", "object", "embed"].includes(tag)) {
        warnLayout("dynamicContent");
      }
    },
    onCloseTag: (tag) => {
      if (tag === "table") tables.pop();
    },
    allowedTags: [
      ...sanitize.defaults.allowedTags,
      "img",
      "style",
      "span",
      "eq",
      "eqn",
      "section",
      "svg",
      "path",
      "line",
      "input",
      "details",
      "summary",
    ],
    // Embedded CSS is document content. CSP still denies scripts, imports and external resources.
    allowVulnerableTags: true,
    allowedAttributes: layoutAllowedAttributes,
    parser: { lowerCaseAttributeNames: false },
    allowedSchemes: ["https", "http", "mailto"],
    allowedSchemesByTag: { img: ["data"] },
    transformTags: {
      a: (tagName, attrs) => {
        const href = attrs.href || "";
        if (href.startsWith("//")) attrs = { ...attrs, href: `https:${href}` };
        else if (href.includes("#") && !/^[a-z][a-z\d+.-]*:/i.test(href)) {
          const hash = href.indexOf("#");
          try {
            if (
              path.resolve(base, decodeURIComponent(href.slice(0, hash))) ===
              path.resolve(file)
            )
              attrs = { ...attrs, href: href.slice(hash) };
          } catch {
            /* The link notice below handles malformed paths. */
          }
        }
        return { tagName, attribs: attrs };
      },
      input: (_, attrs) => {
        if (attrs.type?.toLowerCase() !== "checkbox") {
          return { tagName: "span", attribs: {} };
        }
        const attribs = { type: "checkbox", disabled: "" };
        if (Object.hasOwn(attrs, "checked")) attribs.checked = "";
        return { tagName: "input", attribs };
      },
      // PDF is static: retain the disclosure structure but include its body.
      details: (_, attrs) => ({
        tagName: "details",
        attribs: { ...attrs, open: "" },
      }),
      "*": (tagName, attrs) => {
        const hints = layoutHints(tagName, attrs, tables.at(-1));
        if (hints) {
          const name = `aldus-layout-${hintRules.length}`;
          hintRules.push(`.${name}{${hints}}`);
          attrs = {
            ...attrs,
            class: [attrs.class, name].filter(Boolean).join(" "),
          };
        }
        return { tagName, attribs: attrs };
      },
      img: (_, attrs) => {
        const image = images.get(attrs.src || "");
        if (!image) {
          warnings.push(attrs.src || attrs.alt || "image");
          return {
            tagName: "span",
            attribs: { class: "aldus-missing-image" },
            text: attrs.alt || "[image]",
          };
        }
        const attribs = { ...attrs, alt: attrs.alt || "", src: image.src };
        const height = Number(attrs.height);
        if (image.badge || (height > 0 && height <= 40)) {
          attribs.class = [attrs.class, "aldus-badge"]
            .filter(Boolean)
            .join(" ");
        }
        return { tagName: "img", attribs };
      },
    },
  });
  // Check links after sanitization so notices describe the actual output.
  const targets = new Set(),
    fragments = [];
  sanitize(body, {
    onOpenTag: (tag, attrs) => {
      if (attrs.class?.split(/\s+/).includes("katex-error"))
        warnLayout("mathError");
      if (attrs.id) targets.add(attrs.id);
      if (tag === "a" && attrs.name) targets.add(attrs.name);
      if (tag !== "a" || !attrs.href) return;
      if (attrs.href.startsWith("#")) {
        try {
          fragments.push(decodeURIComponent(attrs.href.slice(1)));
        } catch {
          warnLayout("brokenAnchor");
        }
      } else if (!/^(?:https?:|mailto:)/i.test(attrs.href))
        warnLayout("localLinks");
    },
  });
  if (fragments.some((fragment) => fragment && !targets.has(fragment)))
    warnLayout("brokenAnchor");
  const theme = ["default", "minimal", "dark"].includes(options.theme)
    ? options.theme
    : "default";
  const css = fs.readFileSync(
    path.join(__dirname, "../../resources/themes", `${theme}.css`),
    "utf8",
  );
  let linkColor = "#1565c0";
  if (theme === "dark") linkColor = "#90caf9";
  if (theme === "minimal") linkColor = "#424242";
  const title = source.match(/^#\s+(.+)$/m)?.[1] || path.basename(file);
  const footer =
    options.authorEnabled !== false && options.author
      ? `<div class="aldus-footer">${escape(title)} · © ${escape(options.author)}</div>`
      : "";
  return {
    sourceDiagnostics: checked.diagnostics,
    warnings: [...new Set(warnings)],
    layoutWarnings,
    html: `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src data:; base-uri 'none'; form-action 'none'">
  <style>
    @layer aldus-defaults, aldus-hints;
    ${mathCss}
    @layer aldus-defaults {
      ${css}
      a { color: ${linkColor}; }
      ${documentCss}
      ${layoutCss(options)}
    }
    @layer aldus-hints { ${hintRules.join("\n")} }
  </style>
</head>
<body>${body}${footer}</body>
</html>`,
  };
}

module.exports = { buildDocument };
